#!/bin/bash


# Check for root privileges
if [ "$EUID" -ne 0 ]; then
    echo "Please run this script with sudo."
    exit 1
fi

./install_dependency

sudo -u "$SUDO_USER" ./install_miniconda_clone_vnpy

pushd /home/$SUDO_USER/vnpy
bash install.sh "/home/$SUDO_USER/miniconda3/bin/python"  "https://pypi.vnpy.com"
popd

sudo -u "$SUDO_USER" ./install_vnpackages

# Optionally we can install the mysql server
#./install_mysql

echo "Setup Done."
echo "Next please run: python run.py to start the vnpy GuiAPP"
